apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: reverse-words
  namespace: default
spec:
  host: reverse-words-default.192.168.99.102.nip.io
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: reverse-words
    weight: 100
status:
  ingress: []